import { DatabaseSync } from 'node:sqlite';
import {
  migrate,
  migrateV2,
  migrateV3,
  migrateV4,
  migrateV5,
  migrateV6,
  migrateV7,
  migrateV8,
  migrateV9,
  migrateV10,
  migrateV11,
  migrateV12,
  migrateV13,
  migrateV14,
  migrateV15,
  migrateV16,
  migrateV17,
  migrateV18,
  migrateV19,
  migrateV20,
  migrateV21,
  migrateV22,
  migrateV23,
  migrateV24,
  migrateV25,
  migrateV26,
  migrateV27,
  migrateV28,
  migrateV29,
  migrateV30,
  migrateV31,
  migrateV32,
  migrateV33,
  migrateV34,
  migrateV35,
  migrateV36,
  migrateV37,
  migrateV38,
  migrateV39,
  migrateV40,
  migrateV41,
} from './schema';

export function createTestDb(): DatabaseSync {
  const db = new DatabaseSync(':memory:');
  migrate(db);
  migrateV2(db);
  migrateV3(db);
  migrateV4(db);
  migrateV5(db);
  migrateV6(db);
  migrateV7(db);
  migrateV8(db);
  migrateV9(db);
  migrateV10(db);
  migrateV11(db);
  migrateV12(db);
  migrateV13(db);
  migrateV14(db);
  migrateV15(db);
  migrateV16(db);
  migrateV17(db);
  migrateV18(db);
  migrateV19(db);
  migrateV20(db);
  migrateV21(db);
  migrateV22(db);
  migrateV23(db);
  migrateV24(db);
  migrateV25(db);
  migrateV26(db);
  migrateV27(db);
  migrateV28(db);
  migrateV29(db);
  migrateV30(db);
  migrateV31(db);
  migrateV32(db);
  migrateV33(db);
  migrateV34(db);
  migrateV35(db);
  migrateV36(db);
  migrateV37(db);
  migrateV38(db);
  migrateV39(db);
  migrateV40(db);
  migrateV41(db);
  return db;
}
