import type { ShipCodePlan } from '@shipcode/shared';

export function formatPlanComment(plan: ShipCodePlan): string {
  const sections: string[] = [];

  sections.push(`> [!NOTE]`);
  sections.push(`> This plan was generated by ShipCode. Review and approve it in the ShipCode UI.`);
  sections.push('');

  sections.push(`## Implementation Plan — v${plan.version}`);
  sections.push('');

  sections.push(`**Objective:** ${plan.objective}`);
  sections.push(`**Complexity:** ${plan.estimatedComplexity}`);
  sections.push('');

  // Files table (only if present)
  if (plan.files.length > 0) {
    sections.push(`## Files (${plan.files.length} ${plan.files.length === 1 ? 'file' : 'files'})`);
    sections.push('');
    sections.push(`| Action | Path | Description |`);
    sections.push(`|--------|------|-------------|`);
    for (const file of plan.files) {
      sections.push(`| ${file.action} | ${file.path} | ${file.description} |`);
    }
    sections.push('');
  }

  // Steps section
  sections.push(`## Steps`);
  sections.push('');
  for (const step of plan.steps) {
    sections.push(`${step.order}. **${step.description}**`);
    const fileList = step.files.map((f) => `\`${f}\``).join(', ');
    sections.push(`   Files: ${fileList}`);
    sections.push(`   > ${step.rationale}`);
    sections.push('');
  }

  // Acceptance Criteria (only if present)
  if (plan.acceptanceCriteria.length > 0) {
    sections.push(`## Acceptance Criteria`);
    sections.push('');
    for (const criterion of plan.acceptanceCriteria) {
      sections.push(`- [ ] ${criterion}`);
    }
    sections.push('');
  }

  // Out of Scope (only if present)
  if (plan.outOfScope.length > 0) {
    sections.push(`<details>`);
    sections.push(`<summary>Out of Scope</summary>`);
    sections.push('');
    for (const item of plan.outOfScope) {
      sections.push(`- ${item}`);
    }
    sections.push('');
    sections.push(`</details>`);
    sections.push('');
  }

  // Dependencies (only if present)
  if (plan.dependencies.length > 0) {
    sections.push(`<details>`);
    sections.push(`<summary>Dependencies</summary>`);
    sections.push('');
    for (const dep of plan.dependencies) {
      sections.push(`- ${dep}`);
    }
    sections.push('');
    sections.push(`</details>`);
    sections.push('');
  }

  sections.push(`---`);
  sections.push(`*Generated by ShipCode*`);

  let body = sections.join('\n');

  // Byte-length guard
  const byteLength = Buffer.byteLength(body, 'utf8');
  if (byteLength > 65_000) {
    // Find and replace the Steps section
    const stepsStart = body.indexOf('## Steps');
    const acceptanceStart = body.indexOf('## Acceptance Criteria');
    const outOfScopeStart = body.indexOf('<details>\n<summary>Out of Scope</summary>');
    const dependenciesStart = body.indexOf('<details>\n<summary>Dependencies</summary>');
    const fallbackSectionStart = [acceptanceStart, outOfScopeStart, dependenciesStart]
      .filter((index) => index !== -1)
      .sort((a, b) => a - b)[0];
    const stepsEnd = fallbackSectionStart ?? body.length;
    /* v8 ignore next -- formatted plan comments always contain a Steps section before truncation */
    if (stepsStart !== -1 && stepsEnd > stepsStart) {
      const beforeSteps = body.substring(0, stepsStart);
      const afterSteps = body.substring(stepsEnd);
      const truncatedSteps = `## Steps\n\n_(Truncated — ${plan.steps.length} steps. View full plan in ShipCode UI.)_\n\n`;
      body = beforeSteps + truncatedSteps + afterSteps;
    }
  }

  return body;
}
