#!/usr/bin/env bun
/**
 * Reads each skills/<phase>/SKILL.md, validates its frontmatter and required
 * slots, computes a sha256 version hash, and emits a typed
 * defaults.generated.ts that the runtime loader imports.
 *
 * Run via: bun run build:skills
 *
 * The generated file is committed. CI verifies it is in sync with the
 * source markdown by running this script and checking for git diff.
 */

import { createHash } from 'node:crypto';
import { readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

import { PHASE_SKILL_KEYS, type PhaseSkillKey } from '../packages/shared/src/skills-types';

// Locked to the shared canonical list. Renaming a phase here alone would be a
// no-op; update packages/shared/src/skills-types.ts AND the matching
// skills/<phase>/SKILL.md folder together, or the build below will fail.
const PHASES = PHASE_SKILL_KEYS;

interface ParsedFrontmatter {
  name: string;
  description: string;
  phase: string;
  schemaVersion: number;
  requiredSlots: string[];
}

function parseFrontmatter(
  raw: string,
  source: string,
): {
  frontmatter: ParsedFrontmatter;
  body: string;
} {
  const match = raw.match(/^---\n([\s\S]*?)\n---\n([\s\S]*)$/);
  if (!match) {
    throw new Error(`${source}: no YAML frontmatter found`);
  }
  const [, fmText, body] = match;
  const fm: Record<string, unknown> = {};
  let currentArrayKey: string | null = null;
  for (const line of fmText.split('\n')) {
    if (line.startsWith('  - ')) {
      if (!currentArrayKey) {
        throw new Error(`${source}: unexpected list item without key: ${line}`);
      }
      (fm[currentArrayKey] as string[]).push(line.slice(4).trim());
      continue;
    }
    const m = line.match(/^([a-zA-Z][a-zA-Z0-9_]*):\s*(.*)$/);
    if (!m) continue;
    const [, key, val] = m;
    if (val === '') {
      fm[key] = [];
      currentArrayKey = key;
    } else {
      currentArrayKey = null;
      fm[key] = key === 'schemaVersion' ? Number(val) : val;
    }
  }
  for (const required of ['name', 'description', 'phase', 'schemaVersion', 'requiredSlots']) {
    if (!(required in fm)) {
      throw new Error(`${source}: missing required frontmatter field "${required}"`);
    }
  }
  return { frontmatter: fm as unknown as ParsedFrontmatter, body };
}

function escapeForBacktickTemplate(s: string): string {
  return s.replace(/\\/g, '\\\\').replace(/`/g, '\\`').replace(/\$\{/g, '\\${');
}

const SCRIPT_DIR = dirname(fileURLToPath(import.meta.url));
const REPO_ROOT = join(SCRIPT_DIR, '..');
const SKILLS_DIR = join(REPO_ROOT, 'skills');
const OUT_PATH = join(REPO_ROOT, 'packages/agents/src/skills/defaults.generated.ts');

interface BundledEntry {
  content: string;
  version: string;
  requiredSlots: string[];
  schemaVersion: number;
}

const entries: Record<PhaseSkillKey, BundledEntry> = {} as Record<PhaseSkillKey, BundledEntry>;

for (const phase of PHASES) {
  const path = join(SKILLS_DIR, phase, 'SKILL.md');
  const raw = readFileSync(path, 'utf-8');
  const { frontmatter } = parseFrontmatter(raw, path);

  if (frontmatter.name !== phase) {
    throw new Error(
      `${path}: frontmatter name "${frontmatter.name}" does not match folder name "${phase}"`,
    );
  }
  if (typeof frontmatter.schemaVersion !== 'number' || Number.isNaN(frontmatter.schemaVersion)) {
    throw new Error(`${path}: schemaVersion must be a number, got ${frontmatter.schemaVersion}`);
  }
  if (!Array.isArray(frontmatter.requiredSlots) || frontmatter.requiredSlots.length === 0) {
    throw new Error(`${path}: requiredSlots must be a non-empty array`);
  }

  for (const slot of frontmatter.requiredSlots) {
    if (!raw.includes(`{{${slot}}}`)) {
      throw new Error(
        `${path}: required slot {{${slot}}} declared in frontmatter but not found in body`,
      );
    }
  }

  const version = createHash('sha256').update(raw).digest('hex').slice(0, 16);

  entries[phase] = {
    content: raw,
    version,
    requiredSlots: frontmatter.requiredSlots,
    schemaVersion: frontmatter.schemaVersion,
  };
}

const entryLines = PHASES.map((p) => {
  const e = entries[p];
  return `  '${p}': {
    content: \`${escapeForBacktickTemplate(e.content)}\`,
    version: '${e.version}',
    requiredSlots: ${JSON.stringify(e.requiredSlots)} as const,
    schemaVersion: ${e.schemaVersion},
  },`;
}).join('\n');

const out = `// AUTO-GENERATED by scripts/build-skill-defaults.ts. Do not edit by hand.
// Source files: skills/<phase>/SKILL.md at repo root.
// Regenerate via: bun run build:skills

import { type PhaseSkillKey } from '@shipcode/shared';

export { type PhaseSkillKey, PHASE_SKILL_KEYS } from '@shipcode/shared';

export interface BundledDefault {
  /** Raw markdown including frontmatter. The loader strips frontmatter before sending to the provider. */
  content: string;
  /** sha256 prefix of content; recorded on user override rows as base_version. */
  version: string;
  /** Slot names ({{KEY}}) that any override of this skill MUST contain. */
  requiredSlots: readonly string[];
  /** Bumped when slot vocabulary changes; mismatched user rows are quarantined on startup. */
  schemaVersion: number;
}

export const DEFAULT_SKILLS: Record<PhaseSkillKey, BundledDefault> = {
${entryLines}
};
`;

writeFileSync(OUT_PATH, out, 'utf-8');

console.log(`✓ Wrote ${OUT_PATH}`);
console.log(`  Phases: ${PHASES.length}`);
for (const p of PHASES) {
  const e = entries[p];
  console.log(
    `  - ${p}: schemaVersion=${e.schemaVersion}, slots=[${e.requiredSlots.join(', ')}], ${e.content.length}B, v=${e.version}`,
  );
}
