#!/usr/bin/env bash
#
# sync-agent-memory.sh — regenerate AGENTS.md from per-fact memory files
#
# Source of truth: ~/.agents/memory/*.md (global) + .agents/memory/*.md (repo)
# Outputs:
#   - ~/.codex/AGENTS.md           (global only)
#   - <repo>/AGENTS.md             (global + repo, inlined)
#
# Codex CLI has no @import syntax, so its AGENTS.md must contain the literal
# concatenated memory text. Claude Code and Gemini CLI use @import in their
# respective CLAUDE.md / GEMINI.md bootstrap files, so this script is only
# needed for the Codex side of the triangle.
#
# Idempotent: running twice produces identical output.

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
GLOBAL_MEMORY_DIR="${HOME}/.agents/memory"
REPO_MEMORY_DIR="${REPO_ROOT}/.agents/memory"
GLOBAL_OUTPUT="${HOME}/.codex/AGENTS.md"
REPO_OUTPUT="${REPO_ROOT}/AGENTS.md"
SIZE_WARN_BYTES=28672  # 28 KiB = 80% of Codex's 32 KiB default

write_header() {
  local label="$1"
  cat <<EOF
# AGENTS.md — ${label}

<!--
DO NOT EDIT BY HAND.
Regenerated by scripts/sync-agent-memory.sh from per-fact memory files.
Source of truth:
  - ~/.agents/memory/*.md (global)
  - <repo>/.agents/memory/*.md (repo-scoped)
Edit those files, then run: bash scripts/sync-agent-memory.sh
-->

EOF
}

concat_memory_dir() {
  local dir="$1"
  local section_label="$2"
  [[ -d "$dir" ]] || return 0
  local count=0
  for f in "$dir"/*.md; do
    [[ -e "$f" ]] || continue
    local base
    base="$(basename "$f")"
    # Skip the brief (MEMORY.md) and tracker (BATCH_2_CANDIDATES.md) —
    # they're meta, not source facts.
    case "$base" in
      MEMORY.md|BATCH_2_CANDIDATES.md) continue ;;
    esac
    if [[ $count -eq 0 ]]; then
      printf '\n## %s\n\n' "$section_label"
    fi
    printf -- '---\n### %s\n\n' "$base"
    cat "$f"
    printf '\n'
    count=$((count + 1))
  done
}

size_check() {
  local file="$1"
  local label="$2"
  [[ -f "$file" ]] || return 0
  local bytes
  bytes="$(wc -c < "$file" | tr -d ' ')"
  if [[ "$bytes" -gt "$SIZE_WARN_BYTES" ]]; then
    printf 'WARN: %s is %s bytes (>%s byte soft limit, Codex hard limit is 32 KiB)\n' \
      "$label" "$bytes" "$SIZE_WARN_BYTES" >&2
  else
    printf 'OK:   %s is %s bytes\n' "$label" "$bytes"
  fi
}

# Global → ~/.codex/AGENTS.md
mkdir -p "$(dirname "$GLOBAL_OUTPUT")"
{
  write_header "global (Vincent)"
  concat_memory_dir "$GLOBAL_MEMORY_DIR" "Global memory"
} > "$GLOBAL_OUTPUT"

# Repo → <repo>/AGENTS.md (global first, then repo)
{
  write_header "shipcode"
  concat_memory_dir "$GLOBAL_MEMORY_DIR" "Global memory (from ~/.agents/memory/)"
  concat_memory_dir "$REPO_MEMORY_DIR" "Repo memory (from .agents/memory/)"
} > "$REPO_OUTPUT"

size_check "$GLOBAL_OUTPUT" "~/.codex/AGENTS.md"
size_check "$REPO_OUTPUT"   "<repo>/AGENTS.md"

printf '\nDone. Regenerated:\n  %s\n  %s\n' "$GLOBAL_OUTPUT" "$REPO_OUTPUT"
