#!/usr/bin/env bash
#
# sync-agent-memory.sh — regenerate AGENTS.md from per-fact memory files
#
# Source of truth: ~/.agents/memory/*.md (global) + .agents/memory/*.md (repo)
# Outputs:
#   - ~/.codex/AGENTS.md           (global only)
#   - <repo>/AGENTS.md             (global + repo, inlined)
#
# Codex CLI has no @import syntax, so its AGENTS.md must contain the literal
# concatenated memory text. Claude Code and Gemini CLI use @import in their
# respective CLAUDE.md / GEMINI.md bootstrap files, so this script is only
# needed for the Codex side of the triangle.
#
# Size control (Codex hard-truncates AGENTS.md at 32 KiB):
#   - YAML frontmatter is stripped from inlined bodies (metadata stays in the
#     source files; Codex doesn't need name/type/last_verified).
#   - A memory file with `priority: low` in its frontmatter is NOT inlined —
#     it gets a one-line description + path pointer under "Read on demand",
#     and Codex reads the source file when the topic comes up.
#
# Idempotent: running twice produces identical output.

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
GLOBAL_MEMORY_DIR="${HOME}/.agents/memory"
REPO_MEMORY_DIR="${REPO_ROOT}/.agents/memory"
GLOBAL_OUTPUT="${HOME}/.codex/AGENTS.md"
REPO_OUTPUT="${REPO_ROOT}/AGENTS.md"
SIZE_WARN_BYTES=28672  # 28 KiB = 80% of Codex's 32 KiB default

write_header() {
  local label="$1"
  cat <<EOF
# AGENTS.md — ${label}

<!--
DO NOT EDIT BY HAND.
Regenerated by scripts/sync-agent-memory.sh from per-fact memory files.
Source of truth:
  - ~/.agents/memory/*.md (global)
  - <repo>/.agents/memory/*.md (repo-scoped)
Edit those files, then run: bash scripts/sync-agent-memory.sh
-->

EOF
}

# Read a scalar field from a file's YAML frontmatter (empty if absent).
fm_field() {
  local file="$1" key="$2"
  awk -v key="$key" '
    NR == 1 { if ($0 != "---") exit; next }
    $0 == "---" { exit }
    index($0, key ": ") == 1 { print substr($0, length(key) + 3); exit }
  ' "$file"
}

# Print a file's body with its YAML frontmatter block removed.
strip_frontmatter() {
  awk '
    NR == 1 && $0 == "---" { fm = 1; next }
    fm == 1 { if ($0 == "---") fm = 2; next }
    { print }
  ' "$1"
}

concat_memory_dir() {
  local dir="$1"
  local section_label="$2"
  local pointer_root="$3"  # path prefix shown in "read on demand" pointers
  [[ -d "$dir" ]] || return 0
  local count=0
  local pointers=()
  for f in "$dir"/*.md; do
    [[ -e "$f" ]] || continue
    local base
    base="$(basename "$f")"
    # Skip the brief (MEMORY.md) and tracker (BATCH_2_CANDIDATES.md) —
    # they're meta, not source facts.
    case "$base" in
      MEMORY.md|BATCH_2_CANDIDATES.md) continue ;;
    esac
    if [[ $count -eq 0 ]]; then
      printf '\n## %s\n\n' "$section_label"
    fi
    count=$((count + 1))
    if [[ "$(fm_field "$f" priority)" == "low" ]]; then
      local desc
      desc="$(fm_field "$f" description)"
      pointers+=("- \`${pointer_root}/${base}\` — ${desc:-no description}")
      continue
    fi
    printf -- '---\n### %s\n' "$base"
    strip_frontmatter "$f"
    printf '\n'
  done
  if [[ ${#pointers[@]} -gt 0 ]]; then
    printf -- '---\n### Read on demand (low-priority — open the file when the topic comes up)\n\n'
    printf '%s\n' "${pointers[@]}"
    printf '\n'
  fi
}

size_check() {
  local file="$1"
  local label="$2"
  [[ -f "$file" ]] || return 0
  local bytes
  bytes="$(wc -c < "$file" | tr -d ' ')"
  if [[ "$bytes" -gt "$SIZE_WARN_BYTES" ]]; then
    printf 'WARN: %s is %s bytes (>%s byte soft limit, Codex hard limit is 32 KiB)\n' \
      "$label" "$bytes" "$SIZE_WARN_BYTES" >&2
  else
    printf 'OK:   %s is %s bytes\n' "$label" "$bytes"
  fi
}

# Global → ~/.codex/AGENTS.md
mkdir -p "$(dirname "$GLOBAL_OUTPUT")"
{
  write_header "global (Vincent)"
  concat_memory_dir "$GLOBAL_MEMORY_DIR" "Global memory" "~/.agents/memory"
} > "$GLOBAL_OUTPUT"

# Repo → <repo>/AGENTS.md (global first, then repo)
{
  write_header "shipcode"
  concat_memory_dir "$GLOBAL_MEMORY_DIR" "Global memory (from ~/.agents/memory/)" "~/.agents/memory"
  concat_memory_dir "$REPO_MEMORY_DIR" "Repo memory (from .agents/memory/)" ".agents/memory"
} > "$REPO_OUTPUT"

size_check "$GLOBAL_OUTPUT" "~/.codex/AGENTS.md"
size_check "$REPO_OUTPUT"   "<repo>/AGENTS.md"

printf '\nDone. Regenerated:\n  %s\n  %s\n' "$GLOBAL_OUTPUT" "$REPO_OUTPUT"
