'use client';

import type { GitHubIssueCacheRecord, Thread } from '@shipshitdev/ui';
import dynamic from 'next/dynamic';

const KanbanBoard = dynamic(() => import('@shipshitdev/ui').then((module) => module.KanbanBoard), {
  ssr: false,
});

const now = '2026-04-13T20:00:00.000Z';
const projectId = 'homepage-project';

const issueDefaults = {
  plannerModelOverride: null,
  reviewerModelOverride: null,
  executorModelOverride: null,
  verifierModelOverride: null,
  plannerModelIdOverride: null,
  reviewerModelIdOverride: null,
  executorModelIdOverride: null,
  verifierModelIdOverride: null,
  plannerReasoningEffortOverride: null,
  reviewerReasoningEffortOverride: null,
  executorReasoningEffortOverride: null,
  verifierReasoningEffortOverride: null,
  revisionCountOverride: null,
  linkedPrNumber: null,
  linkedPrUrl: null,
  linkedPrIsDraft: false,
  ciBlocked: false,
  failingChecks: [],
  unresolvedReviewComments: [],
  unresolvedReviewCommentCount: 0,
  prLastSyncAt: null,
  fetchedAt: now,
};

const issues: GitHubIssueCacheRecord[] = [
  {
    id: 'issue-201',
    projectId,
    issueNumber: 201,
    title: 'Support OpenRouter as a pipeline executor',
    body: 'Add OpenRouter as a first-class execution path without breaking verification.',
    labels: ['p0'],
    assignee: 'shipcode',
    state: 'open',
    pipelineStatus: 'planning',
    threadId: 'thread-201',
    claimedAt: now,
    claimedBy: 'shipcode',
    lastPhaseUpdate: now,
    lastStatusLabel: 'agent:planning',
    ...issueDefaults,
    executorModelOverride: 'openrouter',
    executorModelIdOverride: 'openrouter/anthropic/claude-sonnet-4',
  },
  {
    id: 'issue-198',
    projectId,
    issueNumber: 198,
    title: 'Tighten reviewer loop before execution',
    body: 'Keep reviewer findings actionable and revise until the plan is stable.',
    labels: ['p1'],
    assignee: 'shipcode',
    state: 'open',
    pipelineStatus: 'reviewing',
    threadId: 'thread-198',
    claimedAt: now,
    claimedBy: 'shipcode',
    lastPhaseUpdate: now,
    lastStatusLabel: 'agent:reviewing',
    ...issueDefaults,
    reviewerModelOverride: 'codex',
    unresolvedReviewComments: [
      {
        author: 'codex',
        body: 'PipelineContext is still missing executorModelOverride in one path.',
        url: 'https://github.com/shipshitdev/shipcode/pull/243#discussion_r1',
        createdAt: now,
        path: 'packages/pipeline/src/pipeline.ts',
        line: 118,
      },
    ],
    unresolvedReviewCommentCount: 1,
    prLastSyncAt: now,
  },
  {
    id: 'issue-190',
    projectId,
    issueNumber: 190,
    title: 'Render live verifier status in desktop board',
    body: 'Show progress and checkpoint context while the verifier is running.',
    labels: ['p1'],
    assignee: 'shipcode',
    state: 'open',
    pipelineStatus: 'executing',
    threadId: 'thread-190',
    claimedAt: now,
    claimedBy: 'shipcode',
    lastPhaseUpdate: now,
    lastStatusLabel: 'agent:executing',
    ...issueDefaults,
    executorModelOverride: 'claude',
    linkedPrNumber: 243,
    linkedPrUrl: 'https://github.com/shipshitdev/shipcode/pull/243',
    linkedPrIsDraft: true,
  },
  {
    id: 'issue-176',
    projectId,
    issueNumber: 176,
    title: 'Unblock project deletion when worktree root changes',
    body: 'Use path-as-truth cleanup so worktree removal does not recompute from settings.',
    labels: ['p0', 'bug'],
    assignee: null,
    state: 'open',
    pipelineStatus: 'failed',
    threadId: 'thread-176',
    claimedAt: now,
    claimedBy: 'shipcode',
    lastPhaseUpdate: now,
    lastStatusLabel: 'human:failed',
    ...issueDefaults,
    linkedPrNumber: 241,
    linkedPrUrl: 'https://github.com/shipshitdev/shipcode/pull/241',
    linkedPrIsDraft: true,
    ciBlocked: false,
    failingChecks: [
      {
        name: 'typecheck',
        status: 'failed',
        conclusion: 'failure',
        detailsUrl: 'https://github.com/shipshitdev/shipcode/actions/runs/1',
        workflowName: 'CI',
      },
    ],
  },
  {
    id: 'issue-163',
    projectId,
    issueNumber: 163,
    title: 'Polish docs embedding on the web app',
    body: 'Sync exported docs into /public/docs and simplify the deploy path.',
    labels: ['p2'],
    assignee: null,
    state: 'open',
    pipelineStatus: 'todo',
    threadId: null,
    claimedAt: null,
    claimedBy: null,
    lastPhaseUpdate: null,
    lastStatusLabel: null,
    ...issueDefaults,
  },
  {
    id: 'issue-155',
    projectId,
    issueNumber: 155,
    title: 'Move desktop notifications into a dedicated service',
    body: 'Separate notification orchestration from IPC wiring and renderer toast state.',
    labels: ['p2'],
    assignee: 'shipcode',
    state: 'open',
    pipelineStatus: 'completed',
    threadId: 'thread-155',
    claimedAt: now,
    claimedBy: 'shipcode',
    lastPhaseUpdate: now,
    lastStatusLabel: 'done',
    ...issueDefaults,
    linkedPrNumber: 239,
    linkedPrUrl: 'https://github.com/shipshitdev/shipcode/pull/239',
    prLastSyncAt: now,
  },
];

const threadDefaults = {
  prompt: '',
  plannerModel: 'claude',
  reviewerModel: 'codex',
  verifierModel: 'claude',
  executorModel: 'claude',
  clarificationRound: 0,
  clarificationRequest: null,
  clarificationAnswers: [],
  verificationStatus: null,
  verificationRetries: 0,
  autonomous: true,
  baseBranch: 'develop',
  forkPointSha: null,
  githubRepo: 'shipshitdev/shipcode',
  lastError: null,
  createdAt: now,
  updatedAt: now,
  revisorResolvedModel: null,
  executorResolvedModel: null,
  verifierResolvedModel: null,
  totalTokensPrompt: 0,
  totalTokensCompletion: 0,
  totalCostUsd: 0,
  kind: 'pipeline' as const,
  failurePhase: null,
  failureCount: 0,
};

const threads: Thread[] = [
  {
    id: 'thread-201',
    projectId,
    title: 'Support OpenRouter as a pipeline executor',
    status: 'planning',
    worktreeBranch: 'feat/openrouter-tier1',
    worktreePath: '~/.shipcode/worktrees/shipcode/thread-201',
    reviewRound: 0,
    githubIssueNumber: 201,
    githubPrNumber: null,
    plannerResolvedModel: 'claude-opus-4.1',
    reviewerResolvedModel: null,
    ...threadDefaults,
    executorModel: 'openrouter',
  },
  {
    id: 'thread-198',
    projectId,
    title: 'Tighten reviewer loop before execution',
    status: 'reviewing',
    worktreeBranch: 'shipcode/198-review-loop',
    worktreePath: '~/.shipcode/worktrees/shipcode/thread-198',
    reviewRound: 2,
    githubIssueNumber: 198,
    githubPrNumber: null,
    plannerResolvedModel: 'claude-sonnet-4',
    reviewerResolvedModel: 'codex',
    ...threadDefaults,
    revisorResolvedModel: 'claude-sonnet-4',
  },
  {
    id: 'thread-190',
    projectId,
    title: 'Render live verifier status in desktop board',
    status: 'executing',
    worktreeBranch: 'shipcode/190-live-verifier',
    worktreePath: '~/.shipcode/worktrees/shipcode/thread-190',
    reviewRound: 1,
    githubIssueNumber: 190,
    githubPrNumber: 243,
    plannerResolvedModel: 'claude-sonnet-4',
    reviewerResolvedModel: 'codex',
    ...threadDefaults,
    verificationRetries: 1,
    executorResolvedModel: 'claude-sonnet-4',
  },
  {
    id: 'thread-176',
    projectId,
    title: 'Unblock project deletion when worktree root changes',
    status: 'failed',
    worktreeBranch: 'shipcode/176-worktree-root',
    worktreePath: '~/.shipcode/worktrees/shipcode/thread-176',
    reviewRound: 1,
    githubIssueNumber: 176,
    githubPrNumber: 241,
    plannerResolvedModel: 'claude-sonnet-4',
    reviewerResolvedModel: 'codex',
    ...threadDefaults,
    verificationStatus: 'failed',
    verificationRetries: 2,
    lastError: 'Typecheck failed in packages/git/src/worktree.ts',
    revisorResolvedModel: 'claude-sonnet-4',
    executorResolvedModel: 'claude-sonnet-4',
    verifierResolvedModel: 'claude-sonnet-4',
    failurePhase: 'verify',
    failureCount: 2,
  },
  {
    id: 'thread-155',
    projectId,
    title: 'Move desktop notifications into a dedicated service',
    status: 'completed',
    worktreeBranch: 'shipcode/155-notification-service',
    worktreePath: '~/.shipcode/worktrees/shipcode/thread-155',
    reviewRound: 1,
    githubIssueNumber: 155,
    githubPrNumber: 239,
    plannerResolvedModel: 'claude-sonnet-4',
    reviewerResolvedModel: 'codex',
    ...threadDefaults,
    verificationStatus: 'passed',
    executorResolvedModel: 'claude-sonnet-4',
    verifierResolvedModel: 'claude-sonnet-4',
  },
];

export function ProductMockup() {
  return (
    <div className="mx-auto w-full max-w-[1500px] overflow-hidden rounded-[24px] border border-white/8 bg-primary shadow-[0_24px_80px_rgba(0,0,0,0.35)]">
      <div className="h-[640px] overflow-hidden bg-primary">
        <KanbanBoard
          issues={issues}
          threads={threads}
          readOnly
          onIssueClick={() => {}}
          onRefresh={() => {}}
          projectName="ShipCode Dashboard"
          baseBranch="develop"
          branches={['develop', 'main', 'feature/homepage-kanban']}
          onBaseBranchChange={() => {}}
          onRefreshBranches={() => {}}
          repoUrl="https://github.com/shipshitdev/shipcode"
          projectsUrl="https://github.com/shipshitdev/shipcode/projects"
          onOpenExternal={() => {}}
          selectedIssueNumber={198}
        />
      </div>
    </div>
  );
}
